In [1]:
import numpy as np
import pandas as pd
import statsmodels.api as sm
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()

In [2]:
rawdata=pd.read_csv("steam_games.csv")
#rawdata.head()

In [3]:
rawdata.describe(include='all')

,steam_appid,name,developers,publishers,categories,genres,required_age,n_achievements,platforms,is_released,...,additional_content,total_reviews,total_positive,total_negative,review_score,review_score_desc,positive_percentual,metacritic,is_free,price_initial (USD)
count,7.142900e+04,71429,71429,71429,71429,71429,71429.000000,71429.000000,71429,71429,...,71429,7.142900e+04,7.142900e+04,71429.000000,71429.000000,71429,71429.000000,71429.000000,71429,71429.000000
unique,NaN,70990,49545,44187,6995,2373,NaN,NaN,7,2,...,7154,NaN,NaN,NaN,NaN,19,NaN,NaN,2,NaN
top,NaN,Aurora,[],[],"['Single-player', 'Family Sharing']","['Action', 'Indie']",NaN,NaN,['windows'],True,...,[],NaN,NaN,NaN,NaN,No user reviews,NaN,NaN,False,NaN
freq,NaN,4,200,493,12030,3914,NaN,NaN,54889,58041,...,64266,NaN,NaN,NaN,NaN,26812,NaN,NaN,61885,NaN
mean,1.613700e+06,NaN,NaN,NaN,NaN,NaN,2.573227,16.079478,NaN,NaN,...,NaN,4.102497e+02,3.602238e+02,50.025886,2.192849,NaN,46.113290,2.573227,NaN,6.528184
std,8.625559e+05,NaN,NaN,NaN,NaN,NaN,13.591997,138.084319,NaN,NaN,...,NaN,8.389934e+03,7.409672e+03,1171.055349,3.175885,NaN,41.961702,13.591997,NaN,13.186426
min,7.300000e+02,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,NaN,NaN,...,NaN,0.000000e+00,0.000000e+00,0.000000,0.000000,NaN,0.000000,0.000000,NaN,0.000000
25%,9.296400e+05,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,NaN,NaN,...,NaN,0.000000e+00,0.000000e+00,0.000000,0.000000,NaN,0.000000,0.000000,NaN,0.000000
50%,1.533470e+06,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,NaN,NaN,...,NaN,2.000000e+00,2.000000e+00,0.000000,0.000000,NaN,50.000000,0.000000,NaN,2.990000
75%,2.383530e+06,NaN,NaN,NaN,NaN,NaN,0.000000,16.000000,NaN,NaN,...,NaN,1.900000e+01,1.400000e+01,4.000000,5.000000,NaN,88.000000,0.000000,NaN,9.990000
max,3.430140e+06,NaN,NaN,NaN,NaN,NaN,97.000000,9821.000000,NaN,NaN,...,NaN,1.279700e+06,1.107275e+06,172425.000000,9.000000,NaN,100.000000,97.000000,NaN,999.980000

In [4]:
rawdata['price_initial (USD)'] = rawdata['price_initial (USD)'].apply(lambda x: np.nan if isinstance(x, str) else x)
rawdata=rawdata.dropna(subset=['price_initial (USD)'])
rawdata.describe(include='all')
#sns.distplot(rawdata['price_initial (USD)'])
rawdata.to_csv("steam_games op.csv")

In [5]:
rawdata['release_date']=pd.to_datetime(rawdata["release_date"], errors='coerce')
rawdata.head()

,steam_appid,name,developers,publishers,categories,genres,required_age,n_achievements,platforms,is_released,...,additional_content,total_reviews,total_positive,total_negative,review_score,review_score_desc,positive_percentual,metacritic,is_free,price_initial (USD)
0,2719580,勇者の伝説の勇者,['ぽけそう'],['ぽけそう'],"['Single-player', 'Family Sharing']","['Casual', 'Indie']",0,0,['windows'],True,...,[],0,0,0,0.0,No user reviews,0.0,0,False,0.99
1,2719590,Light No Fire,['Hello Games'],['Hello Games'],"['Single-player', 'Multi-player', 'Co-op', 'On...","['Action', 'Adventure']",0,0,['windows'],False,...,[],0,0,0,0.0,No user reviews,0.0,0,False,0.00
2,2719600,Lorhaven: Cursed War,['GoldenGod Games'],['GoldenGod Games'],"['Single-player', 'Multi-player', 'PvP', 'Shar...","['RPG', 'Strategy']",0,32,"['windows', 'mac']",True,...,[],9,8,1,0.0,9 user reviews,88.9,0,False,9.99
3,2719610,PUIQ: Demons,['Giammnn'],['Giammnn'],"['Single-player', 'Steam Achievements', 'Famil...","['Action', 'Casual', 'Indie', 'RPG']",0,28,['windows'],True,...,[],0,0,0,0.0,No user reviews,0.0,0,False,2.99
4,2719650,Project XSTING,['Saucy Melon'],['Saucy Melon'],"['Single-player', 'Steam Achievements', 'Steam...","['Action', 'Casual', 'Indie', 'Early Access']",0,42,['windows'],True,...,[],9,9,0,0.0,9 user reviews,100.0,0,False,7.99

In [6]:
rawdata.isnull().sum()

steam_appid                0
name                       0
developers                 0
publishers                 0
categories                 0
genres                     0
required_age               0
n_achievements             0
platforms                  0
is_released                0
release_date           71401
additional_content         0
total_reviews              0
total_positive             0
total_negative             0
review_score               0
review_score_desc          0
positive_percentual        0
metacritic                 0
is_free                    0
price_initial (USD)        0
dtype: int64

In [7]:
rawdata=rawdata.dropna(axis=0)
rawdata.isnull().sum()

steam_appid            0
name                   0
developers             0
publishers             0
categories             0
genres                 0
required_age           0
n_achievements         0
platforms              0
is_released            0
release_date           0
additional_content     0
total_reviews          0
total_positive         0
total_negative         0
review_score           0
review_score_desc      0
positive_percentual    0
metacritic             0
is_free                0
price_initial (USD)    0
dtype: int64

In [8]:
rawdata.describe(include='all')

,steam_appid,name,developers,publishers,categories,genres,required_age,n_achievements,platforms,is_released,...,additional_content,total_reviews,total_positive,total_negative,review_score,review_score_desc,positive_percentual,metacritic,is_free,price_initial (USD)
count,2.800000e+01,28,28,28,28,28,28.0,28.000000,28,28,...,28,28.00000,28.000000,28.000000,28.000000,28,28.000000,28.0,28,28.000000
unique,NaN,28,28,28,16,22,NaN,NaN,3,1,...,2,NaN,NaN,NaN,NaN,9,NaN,NaN,2,NaN
top,NaN,勇者の伝説の勇者,['ぽけそう'],['ぽけそう'],"['Single-player', 'Family Sharing']","['Casual', 'Indie']",NaN,NaN,['windows'],True,...,[],NaN,NaN,NaN,NaN,No user reviews,NaN,NaN,False,NaN
freq,NaN,1,1,1,7,3,NaN,NaN,25,28,...,27,NaN,NaN,NaN,NaN,12,NaN,NaN,23,NaN
mean,2.719634e+06,NaN,NaN,NaN,NaN,NaN,0.0,14.607143,NaN,NaN,...,NaN,10.25000,9.071429,1.178571,1.000000,NaN,50.614286,0.0,NaN,4.849286
min,2.719130e+06,NaN,NaN,NaN,NaN,NaN,0.0,0.000000,NaN,NaN,...,NaN,0.00000,0.000000,0.000000,0.000000,NaN,0.000000,0.0,NaN,0.000000
25%,2.719298e+06,NaN,NaN,NaN,NaN,NaN,0.0,0.000000,NaN,NaN,...,NaN,0.00000,0.000000,0.000000,0.000000,NaN,0.000000,0.0,NaN,0.990000
50%,2.719680e+06,NaN,NaN,NaN,NaN,NaN,0.0,5.500000,NaN,NaN,...,NaN,1.00000,1.000000,0.000000,0.000000,NaN,78.900000,0.0,NaN,3.990000
75%,2.719928e+06,NaN,NaN,NaN,NaN,NaN,0.0,22.750000,NaN,NaN,...,NaN,3.50000,3.250000,0.250000,0.000000,NaN,100.000000,0.0,NaN,7.990000
max,2.720070e+06,NaN,NaN,NaN,NaN,NaN,0.0,75.000000,NaN,NaN,...,NaN,176.00000,157.000000,19.000000,8.000000,NaN,100.000000,0.0,NaN,13.990000
std,3.131009e+02,NaN,NaN,NaN,NaN,NaN,0.0,20.135355,NaN,NaN,...,NaN,33.54447,29.898506,3.702387,2.509242,NaN,48.320218,0.0,NaN,4.272679